namespace Oppo.Resources.text.help
{
    public static class HelpTextValues
    {
        //General texts
        public const string GeneralUsage    = "Usage:";
        public const string GeneralOptions  = "Options:";

        //Help command
        public const string HelpStartWelcome                = "Welcome to the Open Plug and Produce Orchestration Framework!";
        public const string HelpStartDocuLink               = "For a more detailed documentation visit https://madeupwebsite.oppo/help.html";
        public const string HelpStartUsageDescription       = "oppo [command] <Argument 1> <Argument n> <Options>";
        public const string HelpStartTerminology            = "Terminology:";
        public const string HelpStartOpcuaapp               = "opcua-app:";
        public const string HelpStartOpcuaappDescription    = "and OPC UA server/client Instance generated by oppo";
        public const string HelpStartOppoOptions            = "oppo-options:";
        public const string HelpStartCommand                = "oppo commands";

        public const string BuildCommand    = "Build an oppo project.";
        public const string PublishCommand  = "Publish an oppo project for deployment.";
        public const string NewCommand      = "Create a new oppo Project.";
        public const string HelpCommand     = "Show command line Help.";
        public const string HelloCommand    = "---";
        public const string VersionCommand  = "Display the installed oppo version.";
        public const string CleanCommand    = "Clean a oppo project.";
        public const string DeployStrategy  = "Generate an installer containing the opcua-app.";
        public const string ImportStrategy  = "Import an external ressources.";

        public const string HelpEndCommand  = "Run \"oppo [command] --help\" for more information about a command.";

        //Build command
        public const string BuildFirstLine          = "Build an oppo project.";
        public const string BuildCallDescription    = "oppo build <Options>";

        //Clean command

        //Publish command

        //Deploy command

        //Import command

        //New command

        //Version command


        //Commands description
        public const string BuildHelpArgumentCommandDescription     = "Build help";
        public const string BuildNameArgumentCommandDescription     = "Project name";
        public const string CleanHelpArgumentCommandDescription     = "Clean help";
        public const string CleanNameArgumentCommandDescription     = "Project name";
        public const string DeployHelpArgumentCommandDescription    = "Deploy help";
        public const string DeployNameArgumentCommandDescription    = "Deploy name";
        public const string ImportHelpArgumentCommandDescription    = "Import help";
        public const string NewHelpArgumentCommandDescription       = "New help";
        public const string PublishHelpArgumentCommandDescription   = "Publish help";
        public const string PublishNameArgumentCommandDescription   = "Project name";
        public const string ImportSamplesArgumentCommandDescription = "Import Samples";

    }
}