stages:
  - build-test
  - publish
  - installer
  - integration-test

build-and-test-dotnet-application:
  stage: 'build-test'
  image: 'talsenteam/docker-ci-image-dotnet-core-sdk:v2.1'
  script:    
    - /bin/bash bash-gitlab-ci/run-dotnet-tests.sh
    - /bin/bash bash-gitlab-ci/run-sonarscanner.sh

publish-dotnet-application:
  stage: 'publish'
  image: 'talsenteam/docker-ci-image-dotnet-core-sdk:v2.1'
  artifacts:
    paths:
      -  'publish'
  script:
    - /bin/bash bash-gitlab-ci/run-dotnet-publish.sh

debian-installer:
  dependencies: 
    - 'publish-dotnet-application'
  artifacts:
    paths:
      -  'installer/open62541--v1.0.0.deb'
      -  'installer/appio-terminal.deb'
  stage: 'installer'
  image: 'ubuntu:bionic'
  script:
    - /bin/bash bash-gitlab-ci/run-dpkg-build--open62541--v1.0.0.sh
    - /bin/bash bash-gitlab-ci/run-dpkg-build--appio-terminal.sh

run-integration-test:
  dependencies: 
    - 'debian-installer'
  stage: 'integration-test'
  image: 'talsenteam/docker-ci-image-dotnet-core-runtime:v2.1'
  script:
    - sudo apt-get install -y libmbedtls-dev
    - /bin/bash bash-gitlab-ci/run-dpkg-install--open62541--v1.0.0.sh
    - /bin/bash bash-gitlab-ci/run-dpkg-install--appio-terminal.sh
    - 'chmod 777 /usr/bin/appio' # changed becasue permissions problems
    - /bin/bash bash-gitlab-ci/run-integration-tests.sh
