//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Appio.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UANodeSet xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///           xmlns:uax=&quot;http://opcfoundation.org/UA/2008/02/Types.xsd&quot;
        ///           xmlns=&quot;http://opcfoundation.org/UA/2011/03/UANodeSet.xsd&quot;
        ///           xmlns:s1=&quot;http://yourorganisation.org/example_nodeset/&quot;
        ///           xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///    &lt;NamespaceUris&gt;
        ///        &lt;Uri&gt;http://yourorganisation.org/example_nodeset/&lt;/Uri&gt;
        ///    &lt;/NamespaceUris&gt;
        ///    &lt;Aliases&gt;
        ///&lt;raf&gt;&lt;/raf&gt;
        ///        &lt;Alias Alias=&quot;Boolean&quot;&gt;i=1&lt;/Alias&gt;
        ///        &lt;Al [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xmlFileToValidate_Invalid {
            get {
                return ResourceManager.GetString("xmlFileToValidate_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UANodeSet xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///           xmlns:uax=&quot;http://opcfoundation.org/UA/2008/02/Types.xsd&quot;
        ///           xmlns=&quot;http://opcfoundation.org/UA/2011/03/UANodeSet.xsd&quot;
        ///           xmlns:s1=&quot;http://yourorganisation.org/example_nodeset/&quot;
        ///           xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///    &lt;NamespaceUris&gt;
        ///        &lt;Uri&gt;http://yourorganisation.org/example_nodeset/&lt;/Uri&gt;
        ///    &lt;/NamespaceUris&gt;
        ///    &lt;Aliases&gt;
        ///
        ///        &lt;Alias Alias=&quot;Boolean&quot;&gt;i=1&lt;/Alias&gt;
        ///        &lt;Alias Alias=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xmlFileToValidate_Valid {
            get {
                return ResourceManager.GetString("xmlFileToValidate_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema
        ///    targetNamespace=&quot;http://opcfoundation.org/UA/2011/03/UANodeSet.xsd&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns=&quot;http://opcfoundation.org/UA/2011/03/UANodeSet.xsd&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;UANodeSet&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;NamespaceUris&quot; type=&quot;UriTable&quot; minOccurs=&quot;0&quot;&gt;&lt;/xs:element&gt;
        ///        &lt;xs:element name=&quot;ServerUris&quot; type =&quot;UriTable&quot; minOccurs=&quot;0&quot;&gt;&lt;/xs:el [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xsdFileToValidateAgainst {
            get {
                return ResourceManager.GetString("xsdFileToValidateAgainst", resourceCulture);
            }
        }
    }
}
